SET IDENTITY_INSERT industry ON;

INSERT INTO industry (id, name, created_at, created_by, updated_at, updated_by) VALUES 
(1, 'Enterprise Software', GETUTCDATE(), null, GETUTCDATE(), null), 
(2, 'CRM', GETUTCDATE(), null, GETUTCDATE(), null), 
(3, 'Creative Software', GETUTCDATE(), null, GETUTCDATE(), null), 
(4, 'Database & Enterprise', GETUTCDATE(), null, GETUTCDATE(), null), 
(5, 'Financial Software', GETUTCDATE(), null, GETUTCDATE(), null), 
(6, 'IT Service Management', GETUTCDATE(), null, GETUTCDATE(), null), 
(7, 'HR & Finance', GETUTCDATE(), null, GETUTCDATE(), null), 
(8, 'Video Communications', GETUTCDATE(), null, GETUTCDATE(), null), 
(9, 'E-commerce', GETUTCDATE(), null, GETUTCDATE(), null), 
(10, 'Collaboration Software', GETUTCDATE(), null, GETUTCDATE(), null), 
(11, 'Data Warehousing', GETUTCDATE(), null, GETUTCDATE(), null), 
(12, 'Marketing & Sales', GETUTCDATE(), null, GETUTCDATE(), null), 
(13, 'Digital Agreements', GETUTCDATE(), null, GETUTCDATE(), null), 
(14, 'Team Communication', GETUTCDATE(), null, GETUTCDATE(), null), 
(15, 'Productivity', GETUTCDATE(), null, GETUTCDATE(), null), 
(16, 'Monitoring & Analytics', GETUTCDATE(), null, GETUTCDATE(), null), 
(17, 'Database', GETUTCDATE(), null, GETUTCDATE(), null), 
(18, 'Identity Management', GETUTCDATE(), null, GETUTCDATE(), null), 
(19, 'Communications', GETUTCDATE(), null, GETUTCDATE(), null), 
(20, 'Payments', GETUTCDATE(), null, GETUTCDATE(), null), 
(21, 'Data Analytics', GETUTCDATE(), null, GETUTCDATE(), null), 
(22, 'Design', GETUTCDATE(), null, GETUTCDATE(), null), 
(23, 'Work Management', GETUTCDATE(), null, GETUTCDATE(), null), 
(24, 'Database/Spreadsheet', GETUTCDATE(), null, GETUTCDATE(), null), 
(25, 'DevOps', GETUTCDATE(), null, GETUTCDATE(), null), 
(26, 'Customer Service', GETUTCDATE(), null, GETUTCDATE(), null), 
(27, 'Cloud Storage', GETUTCDATE(), null, GETUTCDATE(), null), 
(28, 'Customer Engagement', GETUTCDATE(), null, GETUTCDATE(), null), 
(29, 'Marketing Automation', GETUTCDATE(), null, GETUTCDATE(), null), 
(30, 'RPA', GETUTCDATE(), null, GETUTCDATE(), null), 
(31, 'Data & AI', GETUTCDATE(), null, GETUTCDATE(), null), 
(32, 'Data Streaming', GETUTCDATE(), null, GETUTCDATE(), null), 
(33, 'Infrastructure', GETUTCDATE(), null, GETUTCDATE(), null), 
(34, 'Search & Analytics', GETUTCDATE(), null, GETUTCDATE(), null), 
(35, 'Incident Response', GETUTCDATE(), null, GETUTCDATE(), null), 
(36, 'Observability', GETUTCDATE(), null, GETUTCDATE(), null), 
(37, 'Web Infrastructure', GETUTCDATE(), null, GETUTCDATE(), null), 
(38, 'Email Delivery', GETUTCDATE(), null, GETUTCDATE(), null), 
(39, 'Email Marketing', GETUTCDATE(), null, GETUTCDATE(), null), 
(40, 'Collaboration', GETUTCDATE(), null, GETUTCDATE(), null), 
(41, 'Writing Assistant', GETUTCDATE(), null, GETUTCDATE(), null), 
(42, 'Scheduling', GETUTCDATE(), null, GETUTCDATE(), null), 
(43, 'Customer Messaging', GETUTCDATE(), null, GETUTCDATE(), null), 
(44, 'Customer Data', GETUTCDATE(), null, GETUTCDATE(), null), 
(45, 'Identity', GETUTCDATE(), null, GETUTCDATE(), null), 
(46, 'Business Intelligence', GETUTCDATE(), null, GETUTCDATE(), null), 
(47, 'Product Analytics', GETUTCDATE(), null, GETUTCDATE(), null), 
(48, 'Log Management', GETUTCDATE(), null, GETUTCDATE(), null), 
(49, 'Cloud Security', GETUTCDATE(), null, GETUTCDATE(), null), 
(50, 'Cybersecurity', GETUTCDATE(), null, GETUTCDATE(), null), 
(51, 'Contact Center', GETUTCDATE(), null, GETUTCDATE(), null), 
(52, 'Life Sciences', GETUTCDATE(), null, GETUTCDATE(), null), 
(53, 'Spend Management', GETUTCDATE(), null, GETUTCDATE(), null), 
(54, 'Financial Operations', GETUTCDATE(), null, GETUTCDATE(), null), 
(55, 'Sales Intelligence', GETUTCDATE(), null, GETUTCDATE(), null), 
(56, 'Experience Management', GETUTCDATE(), null, GETUTCDATE(), null), 
(57, 'Website Building', GETUTCDATE(), null, GETUTCDATE(), null), 
(58, 'Restaurant Tech', GETUTCDATE(), null, GETUTCDATE(), null), 
(59, 'Revenue Intelligence', GETUTCDATE(), null, GETUTCDATE(), null), 
(60, 'Sales Engagement', GETUTCDATE(), null, GETUTCDATE(), null), 
(61, 'Feature Management', GETUTCDATE(), null, GETUTCDATE(), null), 
(62, 'HR & Payroll', GETUTCDATE(), null, GETUTCDATE(), null), 
(63, 'HR & IT', GETUTCDATE(), null, GETUTCDATE(), null), 
(64, 'Equity Management', GETUTCDATE(), null, GETUTCDATE(), null), 
(65, 'Financial APIs', GETUTCDATE(), null, GETUTCDATE(), null), 
(66, 'Card Issuing', GETUTCDATE(), null, GETUTCDATE(), null), 
(67, 'BNPL', GETUTCDATE(), null, GETUTCDATE(), null), 
(68, 'Expense Management', GETUTCDATE(), null, GETUTCDATE(), null), 
(69, 'Corporate Cards', GETUTCDATE(), null, GETUTCDATE(), null), 
(70, 'Travel & Expense', GETUTCDATE(), null, GETUTCDATE(), null), 
(71, 'Life Sciences R&D', GETUTCDATE(), null, GETUTCDATE(), null), 
(72, 'Process Mining', GETUTCDATE(), null, GETUTCDATE(), null), 
(73, 'Search & Discovery', GETUTCDATE(), null, GETUTCDATE(), null), 
(74, 'IoT', GETUTCDATE(), null, GETUTCDATE(), null), 
(75, 'Physical Security', GETUTCDATE(), null, GETUTCDATE(), null), 
(76, 'Privacy & Security', GETUTCDATE(), null, GETUTCDATE(), null), 
(77, 'Endpoint Management', GETUTCDATE(), null, GETUTCDATE(), null), 
(78, 'Data Security', GETUTCDATE(), null, GETUTCDATE(), null), 
(79, 'APM', GETUTCDATE(), null, GETUTCDATE(), null), 
(80, 'Developer Security', GETUTCDATE(), null, GETUTCDATE(), null), 
(81, 'CI/CD', GETUTCDATE(), null, GETUTCDATE(), null), 
(82, 'Field Service', GETUTCDATE(), null, GETUTCDATE(), null), 
(83, 'Construction', GETUTCDATE(), null, GETUTCDATE(), null), 
(84, 'Web Publishing', GETUTCDATE(), null, GETUTCDATE(), null), 
(85, 'Video Platform', GETUTCDATE(), null, GETUTCDATE(), null);

SET IDENTITY_INSERT industry OFF;