SET IDENTITY_INSERT investor ON;

INSERT INTO investor (id, name, created_at, created_by, updated_at, updated_by) VALUES 
(1, 'Bill Gates', GETUTCDATE(), null, GETUTCDATE(), null),
(2, 'Paul Allen', GETUTCDATE(), null, GETUTCDATE(), null),
(3, 'Halsey Minor', GETUTCDATE(), null, GETUTCDATE(), null),
(4, 'Larry Ellison', GETUTCDATE(), null, GETUTCDATE(), null),
(5, 'Hambrecht & Quist', GETUTCDATE(), null, GETUTCDATE(), null),
(6, 'Bob Miner', GETUTCDATE(), null, GETUTCDATE(), null),
(7, 'Dietmar Hopp', GETUTCDATE(), null, GETUTCDATE(), null),
(8, 'Klaus Tschira', GETUTCDATE(), null, GETUTCDATE(), null),
(9, 'Sierra Ventures', GETUTCDATE(), null, GETUTCDATE(), null),
(10, 'Kleiner Perkins', GETUTCDATE(), null, GETUTCDATE(), null),
(11, 'JMI Equity', GETUTCDATE(), null, GETUTCDATE(), null),
(12, 'Sequoia Capital', GETUTCDATE(), null, GETUTCDATE(), null),
(13, 'Greylock Partners', GETUTCDATE(), null, GETUTCDATE(), null),
(14, 'NEA', GETUTCDATE(), null, GETUTCDATE(), null),
(15, 'Emergence', GETUTCDATE(), null, GETUTCDATE(), null),
(16, 'Bessemer', GETUTCDATE(), null, GETUTCDATE(), null),
(17, 'FirstMark', GETUTCDATE(), null, GETUTCDATE(), null),
(18, 'Felicis', GETUTCDATE(), null, GETUTCDATE(), null),
(19, 'Accel Partners', GETUTCDATE(), null, GETUTCDATE(), null),
(20, 'Sequoia', GETUTCDATE(), null, GETUTCDATE(), null),
(21, 'ICONIQ', GETUTCDATE(), null, GETUTCDATE(), null),
(22, 'Altimeter', GETUTCDATE(), null, GETUTCDATE(), null),
(23, 'General Catalyst', GETUTCDATE(), null, GETUTCDATE(), null),
(24, 'Google Ventures', GETUTCDATE(), null, GETUTCDATE(), null),
(25, 'Accel', GETUTCDATE(), null, GETUTCDATE(), null),
(26, 'Andreessen Horowitz', GETUTCDATE(), null, GETUTCDATE(), null),
(27, 'Index Ventures', GETUTCDATE(), null, GETUTCDATE(), null),
(28, 'USV', GETUTCDATE(), null, GETUTCDATE(), null),
(29, 'Greylock', GETUTCDATE(), null, GETUTCDATE(), null),
(30, 'Union Square', GETUTCDATE(), null, GETUTCDATE(), null),
(31, 'Khosla Ventures', GETUTCDATE(), null, GETUTCDATE(), null),
(32, 'Founders Fund', GETUTCDATE(), null, GETUTCDATE(), null),
(33, 'In-Q-Tel', GETUTCDATE(), null, GETUTCDATE(), null),
(34, 'Bond', GETUTCDATE(), null, GETUTCDATE(), null),
(35, 'Sapphire Ventures', GETUTCDATE(), null, GETUTCDATE(), null),
(36, 'Insight', GETUTCDATE(), null, GETUTCDATE(), null),
(37, 'Benchmark', GETUTCDATE(), null, GETUTCDATE(), null),
(38, 'Thrive Capital', GETUTCDATE(), null, GETUTCDATE(), null),
(39, 'Goldman Sachs', GETUTCDATE(), null, GETUTCDATE(), null),
(40, 'Matrix Partners', GETUTCDATE(), null, GETUTCDATE(), null),
(41, 'DFJ', GETUTCDATE(), null, GETUTCDATE(), null),
(42, 'Index', GETUTCDATE(), null, GETUTCDATE(), null),
(43, 'Sequoia Capital India', GETUTCDATE(), null, GETUTCDATE(), null),
(44, 'Summit Partners', GETUTCDATE(), null, GETUTCDATE(), null),
(45, 'IVP', GETUTCDATE(), null, GETUTCDATE(), null),
(46, 'GV', GETUTCDATE(), null, GETUTCDATE(), null),
(47, 'Mayfield', GETUTCDATE(), null, GETUTCDATE(), null),
(48, 'Trinity', GETUTCDATE(), null, GETUTCDATE(), null),
(49, 'Tenaya', GETUTCDATE(), null, GETUTCDATE(), null),
(50, 'August Capital', GETUTCDATE(), null, GETUTCDATE(), null),
(51, 'JK&B Capital', GETUTCDATE(), null, GETUTCDATE(), null),
(52, 'Venrock', GETUTCDATE(), null, GETUTCDATE(), null),
(53, 'Foundry Group', GETUTCDATE(), null, GETUTCDATE(), null),
(54, 'Bootstrapped', GETUTCDATE(), null, GETUTCDATE(), null),
(55, 'OpenView', GETUTCDATE(), null, GETUTCDATE(), null),
(56, 'Sapphire', GETUTCDATE(), null, GETUTCDATE(), null),
(57, 'CapitalG', GETUTCDATE(), null, GETUTCDATE(), null),
(58, 'Battery', GETUTCDATE(), null, GETUTCDATE(), null),
(59, 'TPG', GETUTCDATE(), null, GETUTCDATE(), null),
(60, 'Lightspeed', GETUTCDATE(), null, GETUTCDATE(), null),
(61, 'Warburg Pincus', GETUTCDATE(), null, GETUTCDATE(), null),
(62, 'Khosla', GETUTCDATE(), null, GETUTCDATE(), null),
(63, 'Scale', GETUTCDATE(), null, GETUTCDATE(), null),
(64, 'Adams Street', GETUTCDATE(), null, GETUTCDATE(), null),
(65, 'Partech', GETUTCDATE(), null, GETUTCDATE(), null),
(66, 'Emergence Capital', GETUTCDATE(), null, GETUTCDATE(), null),
(67, 'Crosslink', GETUTCDATE(), null, GETUTCDATE(), null),
(68, 'Bank of America', GETUTCDATE(), null, GETUTCDATE(), null),
(69, 'TA Associates', GETUTCDATE(), null, GETUTCDATE(), null),
(70, 'Carlyle', GETUTCDATE(), null, GETUTCDATE(), null),
(71, 'Insight Partners', GETUTCDATE(), null, GETUTCDATE(), null),
(72, 'Madrona', GETUTCDATE(), null, GETUTCDATE(), null),
(73, 'TCV', GETUTCDATE(), null, GETUTCDATE(), null),
(74, 'Tiger Global', GETUTCDATE(), null, GETUTCDATE(), null),
(75, 'Coatue', GETUTCDATE(), null, GETUTCDATE(), null),
(76, 'Thrive', GETUTCDATE(), null, GETUTCDATE(), null),
(77, 'Lone Pine', GETUTCDATE(), null, GETUTCDATE(), null),
(78, 'Meritech', GETUTCDATE(), null, GETUTCDATE(), null),
(79, 'Spark', GETUTCDATE(), null, GETUTCDATE(), null),
(80, 'HarbourVest', GETUTCDATE(), null, GETUTCDATE(), null),
(81, 'Spark Capital', GETUTCDATE(), null, GETUTCDATE(), null),
(82, 'Redpoint', GETUTCDATE(), null, GETUTCDATE(), null),
(83, 'Greenoaks', GETUTCDATE(), null, GETUTCDATE(), null),
(84, 'DST Global', GETUTCDATE(), null, GETUTCDATE(), null),
(85, 'Ribbit Capital', GETUTCDATE(), null, GETUTCDATE(), null),
(86, 'Addition', GETUTCDATE(), null, GETUTCDATE(), null),
(87, 'Lux Capital', GETUTCDATE(), null, GETUTCDATE(), null),
(88, 'Arena Holdings', GETUTCDATE(), null, GETUTCDATE(), null),
(89, 'Durable Capital', GETUTCDATE(), null, GETUTCDATE(), null),
(90, 'Softbank', GETUTCDATE(), null, GETUTCDATE(), null),
(91, 'Salesforce Ventures', GETUTCDATE(), null, GETUTCDATE(), null),
(92, 'Tiger', GETUTCDATE(), null, GETUTCDATE(), null),
(93, 'Qumra', GETUTCDATE(), null, GETUTCDATE(), null),
(94, 'Generation IM', GETUTCDATE(), null, GETUTCDATE(), null),
(95, 'DFJ Growth', GETUTCDATE(), null, GETUTCDATE(), null),
(96, 'IAC', GETUTCDATE(), null, GETUTCDATE(), null);

SET IDENTITY_INSERT investor OFF;